Define initial dumper command behaviour

diff --git a/bin/dumper b/bin/dumper
--- a/bin/dumper
+++ b/bin/dumper
@@ -1,6 +1,48 @@
 #!/bin/bash
 
+# Check if no parameters received
+[ $# -eq 0 ] && echo -e "\e[31mNo parameters received\e[0m\nTry using the \e[33m--help\e[0m flag to get aditional information" && exit 1
 params=$*
-echo $params
-unset params
 
+# Set execution directory
+execution_path=$0
+[ -z "$(echo "$execution_path" | grep "^/")" ] && execution_path="$(pwd)/$execution_path"
+execution_path=$(echo "$execution_path" | sed -e "s|/dumper||")/..
+
+# # Load dependencies
+source "$execution_path"/lib/flagger.sh
+source "$execution_path"/lib/inihandler.sh
+
+# Display help if requested
+[ $(hasFlag --help $*) -eq 1 ] && echo -e "\n$(cat "$execution_path"/src/dumper/help)\n" && exit
+params=$(pruneFlag --help $params)
+
+# Check output folder
+output_folder=$(getFlagValue --output-folder $params) && params=$(pruneFlagValue --output-folder $params)
+[ -z "$output_folder" ] && echo -e "\e[31mExecution Exception:\e[0m No output folder defined. Use \e[33m--output-folder\e[0m option to define it" && exit 1
+[ ! -d "$output_folder" ] && mkdir -p "$output_folder"
+[ -d "$output_folder"/struct ] && rm -rf "$output_folder"/struct
+mkdir -p "$output_folder"/struct
+[ -d "$output_folder"/data ] && rm -rf "$output_folder"/data
+mkdir -p "$output_folder"/data
+
+# Check if GTID must be ignored
+has_gtid=$(hasFlag --no-gtid $params) && params=$(pruneFlag --no-gtid $params)
+
+# Check non valid extra params
+params_array=(${params// / })
+[ ${#params_array[@]} -gt 1 ] && echo -e "\e[31mExeciton Exception:\e[0m No valid parameters received. Try using the \e[33m--help\e[0m flag to see valid options" && exit 1
+
+# Check file located at vars_path
+vars_path=$params
+[ -z "$vars_path" ] && echo -e "\e[31mExecution Exception:\e[0m Path to credentials file not defined" && exit 1
+[ ! -f "$vars_path" ] && echo -e "\e[31mExecution Exception:\e[0m File not found at \e[33m$vars_path\e[0m" && exit 1
+
+# Build commands parameters
+command_parameters="$output_folder $(getINIVar $vars_path dbhost) $(getINIVar $vars_path dbuser) $(getINIVar $vars_path dbpwd) $(getINIVar $vars_path dbname) $has_gtid"
+
+# Dump all data
+"$execution_path"/src/dumper/cmd/dump-all.sh $command_parameters
+
+# Report error if has to
+[ $? -ne 0 ] && exit 1
